# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'

text_color_theme: ocean #eg: default | dark | forest | ocean | chocolate | orange
## Base settings ##
url: https://jed1978.github.io #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: Jed's blog
description: > #this means to ignore newlines until "nav_lists:"
  寫程式是一件快樂的事，期許自己可以一輩子都能享受這種快樂

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about.html

paths:
  base: /
  home: /
  all:  /all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: jed1978/jed1978.github.io #e.g. someone/someone.github.io
repository_tree: master #e.g. master

## Language & timezone ##
lang: zh-Hant #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Taipei #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Jed Lin
  # email:  #your Email address e.g. someone@site.com
  facebook: jed.motor #your Facebook username
  # twitter:  #your Twitter username
  # github:  #your GitHub username
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  linkedin: jed-lin #your Linkedin username

## TOC
toc:
  # selectors: 'h1,h2,h3'

## Comment system (Disqus) ##
disqus:
  # shortname:  #the Disqus shortname for the site

## Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  # clientID:  #Github Application Client ID
  # clientSecret:  #Github Application Client Secret
  # repository:  #Github repo
  # owner:  #Github repo owner
  # admin: #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    # - owner

## Google Analytics ##
ga_tracking_id: UA-118355316-1 #Google analytics id for the site

## Reading quantity (LeanCloud) ##
leancloud:
  app_id: BuUewe6j2cBjEJEW5dd3y3Pj-gzGzoHsz #LeanCloud App id
  app_key: rDYdTnuqLkp0vXQrzSILDpAU #LeanCloud App key
  app_class: Counter #LeanCloud App class

# mathjax: true
# mathjax_autoNumber: true
mermaid: true
# chart: true

## Paginate ##
paginate: 7
paginate_path: /page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Sources ##
# sources: bootcss #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"